### ISSUE TITLE
Adjust the size of the svg in the ArticleFingerprint: some fingerprint not fully displayed 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#137]
const ArticleFingerprint = ({
  stats={},
  cells=[],
  // max radius
  radius=100,
  // this space is needed for the text elements
  marginTop=20, marginLeft=20, marginRight=20, marginBottom=20
}) => {
  const angleD = (Math.PI * 2) / (cells.length + 1)
  const svgWidth = radius*2 + marginLeft + marginRight
  const svgHeight = radius*2 + marginTop + marginBottom

try to play with radius and margin but doesn't seem enough

<img width="494" alt="Screenshot 2021-07-14 at 16 47 54" src="https://user-images.githubusercontent.com/35602279/125642658-43dc5be8-e24e-48ab-ae08-e605143464e3.png">

**Comment by biumiamy** [comment]
In _ArticleFingerprint.js_ I manipulated the following lines (and all other things that Daniele mentioned to me in the video we recorded)
`radius=100,` - but manipulating this doesn't work (anymore) - See below
`.exponent(0.25)` to 0.5 or 0.75, but it leads to mixed results... there are just some code lines that are just much longer than others

And in _IssueArticleGridItem_:
`<ArticleFingerprint stats={article.data.stats}  cells={article.data.cells} radius={(size - 20)/2}/>` - Because of this, I suspect the radius in the other js-file doesn't have such an effect anymore. However, manupulating the size here or the substracting, moves the fingerprint around on the canvas.. not the perfect solution either

**Comment by danieleguido** [comment]
Hi @biumiamy @eliselavy I've fixed the issue, the naming of the properties were too ambiguous.
I merged the PR in develop, you should be able to see the results on the dev server.
I also refactored the Cell rendering and moved to a separate component `ArticleFingerprintCellGraphics`. There, the `offsetRadius` property is used to position the small circles at a certain distance from the `originRadius`

```javascript
const ArticleFingerprint = ({
  stats={},
  cells=[],
  // svg dimension (squared). Radius is calculated based on this. R = (size/2 - margin) * 2/3
  size=100,
// draws the circles min-max
  debug=false,
  // this space is needed for the text elements
  margin=20,
```
