### ISSUE TITLE
Clarify the use of markdown table 

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#143]
Clarify the use of markdown table 

Example this table displayed in jupyter notebook but not in the front end (and also not in git)

|Absence||Affect||Equality|
|----||----||----|
|airbrushing||pride||feminism|
|silencing||honour||gender|
|erasure||legacy||fighting|
|forgotten||bravery/heroism||freedom/liberation|
|recognition||inspiration||the proclamation|

Editor|1641|1798|1916
---|---|---|---
Senan|0.55|0.4|0.3
Henry|0.71|0.5|0.63

**Comment by danieleguido** [comment]
Header must be fixed to meet our markdown flavour (only one pipe separator in the header). If you use:
```
|Absence|Affect|Equality|
|----|----|----|
```
instead of 
```
|Absence||Affect||Equality|
|----||----||----|
```
you get the expected result:

|Absence|Affect|Equality|
|----|----|----|
|airbrushing||pride||feminism|
|silencing||honour||gender|
|erasure||legacy||fighting|
|forgotten||bravery/heroism||freedom/liberation|
|recognition||inspiration||the proclamation|

**Comment by danieleguido** [comment]
See https://github.github.com/gfm/#tables-extension- (we can add this link to the Guideline)
