### ISSUE TITLE
11 references undefined in the editorial  - ref.type in ArticleReference.js / gif not displayed figure-2

### ISSUE THREAD

**Issue by eliselavy** [C2DH/journal-of-digital-history#196]
<img width="988" alt="Screenshot 2021-09-30 at 09 19 58" src="https://user-images.githubusercontent.com/35602279/135405974-cfd635f6-bd96-40b6-94e7-4c01b296124a.png">

Look at /src/models/ArticleReference.js

**Comment by eliselavy** [comment]
@inactinique can you redefine firstname lastname orcid badge role? history groupe institution?

**Comment by inactinique** [comment]
I have found the problem of the undefined elements: it's when you cite the same elements several time. THe second time you cite it, it will propose you two choices (one because you already cited it, the other one because it's in the zotero library). If you pick up the first one, it does not work. It seems to work if you pick the second choice.

**Comment by inactinique** [comment]
> @inactinique can you redefine firstname lastname orcid badge role? history groupe institution?

Not sure to see what you mean?

**Comment by eliselavy** [comment]
@inactinique oupps wrong issue let me put the comment o nthe appropriate one
