### ISSUE TITLE
Automatic numbering of figures

### ISSUE THREAD

**Issue by biumiamy** [C2DH/journal-of-digital-history#423]
To make the life of authors and editors easier, we should (finally) go for an automatic numbering of the figures. 
(The guideline should be adjusted accordingly as well.)

**Comment by danieleguido** [comment]
Hi @biumiamy can you check the https://github.com/C2DH/journal-of-digital-history/pull/442 ? 
I've created an article with automatic numbering here: https://github.com/C2DH/jdh-notebook/blob/master/examples/cite-figures-automatic.ipynb

You just have to put the magic suffix `-*` at the end of the usual tagging for figures and tables - so that they are still referencing a specific content: 
![Screenshot 2022-05-12 at 17 16 08](https://user-images.githubusercontent.com/1181642/168109220-adaf59ce-2745-4740-8271-cde291304c55.png)

**Comment by biumiamy** [comment]
which notebook viewer did you use? It didnt work for me.. it just shows the name with the "-*" at the end

**Comment by danieleguido** [comment]
The feature works only in our journal. the -* allows the internal links to be used in the editor instead of "Fig. n" so that it doesn't break the current behaviour in mybinder or in jupyterlab

**Comment by eliselavy** [comment]
@biumiamy guidelines should be updated accordingly

**Comment by danieleguido** [comment]
I close this for now, let's move the discussion (if needed) in #327
