### ISSUE TITLE
Menu missing in the archived version of the site on archive.org 

### ISSUE THREAD

**Issue by lwieneke** [C2DH/journal-of-digital-history#489]
The archived version of the journal does not contain the menu bar which makes accessing the issues and articles difficult
<img width="1578" alt="2022-11-15_10-52-24" src="https://user-images.githubusercontent.com/1942767/201888331-3aabdce1-7cbb-43a9-9b83-715f3624147a.png">

**Comment by eliselavy** [comment]
https://web.archive.org/web/20220607131954/https://journalofdigitalhistory.org/en

**Comment by eliselavy** [comment]
Need to close the pop-up in order to see it:
<img width="1434" alt="Screenshot 2022-11-17 at 12 05 00" src="https://user-images.githubusercontent.com/35602279/202430087-d8adebb7-05f5-439b-93c1-33e9dd6150c6.png">

TO DO: contact people of the BNL Ben and Yves in order to know more about it as there are some problems to select the article

**Comment by lwieneke** [comment]
Can we get a better understanding on what the issue actually is? I hesitate a bit to confront them just with an ominous issue without giving details.

**Comment by danieleguido** [comment]
closing :)
